#!/bin/bash


## Install cygwin packages
echo Installing cygwin packages...

curl https://www.cygwin.com/setup-x86_64.exe -O && mv -f setup-x86_64.exe /setup-x86_64.exe
/setup-x86_64.exe -q -P ssh,vim,gcc-g++,make

echo -n "Waiting for Cygwin Setup to complete."
sleep 1
while ps -W | grep setup-x86_64 > /dev/null; do
    echo -n "."
    sleep 1
done
echo
sleep 1


## Git config
echo Configuring Git...

if ! which git; then
    winget install Git.Git
fi

echo "Use email address:"

declare -a arr=("sbaker48@gmail.com" "sbaker@logikos.com")
for i in "${!arr[@]}"; do
    echo "    $i) ${arr[$i]}"
done

read -p "Select email > " email_sel

git config --global user.name "Sean Baker"
git config --global user.email "${arr[${email_sel:-0}]}"
git config --global core.editor vim
git config --global core.autocrlf false


## Copy files
echo Copying cygwin files...

for f in ./cygwin/files/.[a-z]* ./cygwin/files/[a-z]*; do
  cp -ri "$f" "${HOME}"
done


## Setup security keys
echo Setting up security keys...

if [ ! -s "${HOME}/.ssh/id_rsa" ]; then
    mkdir -p "${HOME}/.ssh"
    chmod 700 "${HOME}/.ssh"
    ssh-keygen -t rsa -f "${HOME}/.ssh/id_rsa"
fi


## Cache file credentials
echo Caching file credentials...

if [ ! -s /etc/nsswitch.conf.bak ]; then cp /etc/nsswitch.conf /etc/nsswitch.conf.bak; fi
mkpasswd -l -c > /etc/passwd
mkgroup -l -c > /etc/group
echo 'passwd: files' > /etc/nsswitch.conf
echo 'group: files' >> /etc/nsswitch.conf


## Setup shortcuts
echo Setting up shortcuts...

cd ${HOME}
ln -s "$(cygpath --desktop)"
ln -s "$(cygpath --mydocs)"
ln -s "$(cygpath --folder 38)"
ln -s "$(cygpath --folder 42)"
ln -s "$(realpath $(cygpath --desktop)/../Downloads)"


## Install common applications

prompt_yn()
{
    p=$1
    d=$2
    read -p "$p " res
    if [ -n "$d" ]; then
        res=${res:-${d}}
    fi
    res=${res,,}
    res=${res:0:1}
    echo $res
}


r=$(prompt_yn "Install applications? [Yes/no/all]" "y")
if [[ "$r" == "y" || "$r" == "a" ]]; then

    if [[ "$r" == "a" || $(prompt_yn "Install Chrome? [Yes/no]") == "y" ]]; then
        winget install Google.Chrome.EXE
    fi

    if [[ "$r" == "a" || $(prompt_yn "Install Perl? [Yes/no]") == "y" ]]; then
        winget install StrawberryPerl.StrawberryPerl
    fi

    if [[ "$r" == "a" || $(prompt_yn "Install 7zip? [Yes/no]") == "y" ]]; then
        winget install 7zip.7zip
    fi

    if [[ "$r" == "a" || $(prompt_yn "Install Notepad++? [Yes/no]") == "y" ]]; then
        winget install Notepad++.Notepad++
    fi

    if [[ "$r" == "a" || $(prompt_yn "Install TortoiseGit? [Yes/no]") == "y" ]]; then
        winget install TortoiseGit.TortoiseGit
    fi

    if [[ "$r" == "a" || $(prompt_yn "Install PuTTY? [Yes/no]") == "y" ]]; then
        winget install PuTTY.PuTTY
    fi

fi

