#!/bin/bash

host="$1"
login="sean"

if [ -z "$host" ]; then
  host="home"
fi


which ssh > /dev/null || exit 2
which ssh-keygen > /dev/null || exit 2

host_ok=0

ping=$(which ping)
if [ "${ping,,}" = "/bin/ping" -o "${ping,,}" = "/usr/bin/ping" ]; then
  if ping -c 1 -W 1 "$host" > /dev/null; then
    host_ok=1
  fi
elif [ "${ping,,}" = "/cygdrive/c/windows/system32/ping" ]; then
  if ping -n 1 -w 1000 "$host" > /dev/null; then
    host_ok=1
  fi
fi

if [ $host_ok -eq 0 ]; then
  echo "$0: Host $host not reachable."
  exit 2
fi

rsa="${HOME}/.ssh/id_rsa"

if [ ! -r "${HOME}/.ssh/id_rsa" ]; then
   ssh-keygen -t rsa -f "${HOME}/.ssh/id_rsa"
fi

#ssh "${login}@${host}" mkdir -p .ssh
cat "${HOME}/.ssh/id_rsa.pub" | ssh "${login}@${host}" 'cat >> .ssh/authorized_keys'

echo "$0: Done."
